### ISSUE TITLE
Gradle Sync 

### ISSUE THREAD

**Issue by Yavar007** [titanium-codes/LocGetter#1]
Hi 

thanks for this library but i cant compile my app it says failed to resolve com.android.support:design:26.1.0

**Comment by blainepwnz** [comment]
hi 
I think you should add into root build.gradle something like this.

allprojects {
    repositories {
        jcenter()
        maven { url "https://oss.sonatype.org/content/groups/public/" }
        maven {
            url 'https://maven.google.com'
        }
    }
}

**Comment by blainepwnz** [comment]
Updated README.
Use recommended option to add library into your app.
