### ISSUE TITLE
Need timout - Taking infinite time to connect, on few devices

### ISSUE THREAD

**Issue by merlinJeyakumar** [titanium-codes/LocGetter#11]
i used below code to retrieve & subscribe location updates , in Doze mode or Batterysaver enabled devices Location could not get connected, so it want to get **TimedOut**

`locationGetter.getLatestLocations()
                .observeOn(AndroidSchedulers.mainThread())
                .doOnError(throwable -> {
                    throwable.printStackTrace();
                    Log.e(TAG, "startLocationUpdates: doOnError " + throwable);
                })
                .subscribe(this::setSuccessResult, throwable -> {
                    setFailureResult(new Exception(throwable));
                    throwable.printStackTrace();
                });`

**Comment by blainepwnz** [comment]
Adding timeout can break backward compatibility, please use timeout operator from rxjava
