### ISSUE TITLE
Need custom request

### ISSUE THREAD

**Issue by merlinJeyakumar** [titanium-codes/LocGetter#12]
Need builder function to setManualRequest for configuring FastInterval, Interval and Priority

Required: Please let me to set requestOption

`        return LocationRequest.create()
                .setFastestInterval(TimeUnit.SECONDS.toMillis(5))
                .setInterval(TimeUnit.SECONDS.toMillis(10))
                .setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY);`

**Comment by blainepwnz** [comment]
high accuracy is set by default
to set specific interval - you can use rx.
Something like this should work fine
```
Observable.timer(5000, TimeUnit.MILLISECONDS)
    .flatMapSingle { LocationGetter.getLatestLocation() }
```
